# Paste with middle click
[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

# Font Size 
[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
action = "IncreaseFontSize"
[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "DecreaseFontSize"
[[keyboard.bindings]]
key = "R"
mods = "Control|Shift"
action = "ResetFontSize"

