# Paste with middle click
[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"
# Font Size 
[[keyboard.bindings]]
key = "H"
mods = "Control|Shift"
action = "IncreaseFontSize"
[[keyboard.bindings]]
key = "G" 
mods = "Control|Shift" 
action = "DecreaseFontSize"
[[keyboard.bindings]]
key = "R"
mods = "Control|Shift"
action = "ResetFontSize"
